name: Deploy Files to Firebase Storage

on:
  push:
    branches:
      - main # eller den branchen du ønsker å deploye fra

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Eller hvilken Node.js-versjon du foretrekker

      - name: Setup Firebase Service Account Key
        run: echo '${{ secrets.FIREBASE_STORAGE }}' > serviceAccountKey.json

      - name: Install dependencies
        run: npm install firebase-admin # Legg til dine nødvendige npm pakker her

      - name: Upload Files to Firebase Storage
        run: node uploadfirebase/uploadToFirebase.js
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/serviceAccountKey.json
