name: Upload Files to Firebase Storage

on:
  push:
    branches:
      - main # Sett dette til branchen du bruker for deployment

jobs:
  upload_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Bruk den Node.js-versjonen som passer for ditt prosjekt

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate Firebase
      run: echo '${{ secrets.firebase_storage }}' > ./firebase-key.json && firebase login:ci --no-localhost --token $(firebase login:ci --no-localhost --interactive)

    - name: Upload Files to Firebase Storage
      run: node uploadfirebase/uploadToFirebase.js
      env:
        FIREBASE_KEY_PATH: './firebase-key.json'
